import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {
  BellRing, Bot, FileOutput, FolderInput, Map, Mic2, Network, Search,
} from "lucide-react";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({
  title: "NeuVault Product — The Complete Document Intelligence Workspace",
  description: "Explore NeuVault automatic intake, document intelligence, linked documents, Map, notes and voice, Nova, Attention and conversion workflows.",
  path: "/product",
});

const features = [
  { id: "automatic-intake", title: "Automatic Intake", icon: FolderInput, copy: "Monitor selected folders on Windows and macOS. Connect Gmail or Microsoft email on desktop, choose a fixed historical range or a start date, and optionally continue monitoring future attachments. Yahoo support is coming soon.", details: ["Watched desktop folders", "Historical and continued email imports", "Manual uploads and mobile scanning", "Written notes and voice recordings"] },
  { id: "document-intelligence", title: "Document Intelligence", icon: Search, copy: "Turn unstructured files into organized, searchable information. NeuVault can create summaries and tags, assign groups and subgroups, identify document types, extract structured details and surface important dates.", details: ["Summaries and tags", "Groups and subgroups", "Extracted data and dates", "Attention signals"] },
  { id: "linked-documents", title: "Linked Documents", icon: Network, copy: "Connect agreements, invoices, notes and supporting records around every context where they matter. Review relationship suggestions, including relevant attachments from the same sender.", details: ["Direct document links", "Linked-document groups", "Document-to-note connections", "Suggested relationships"] },
  { id: "map", title: "The NeuVault Map", icon: Map, copy: "Use a spatial document workspace to arrange nodes, open and read documents, edit notes, compare information side by side and ask Nova to perform supported organizational actions.", details: ["Document and note nodes", "Split-screen reading and editing", "Document and note comparison", "Nova actions and note merging"] },
  { id: "notes-voice", title: "Notes and Voice", icon: Mic2, copy: "Write notes manually or with Nova, select supporting files before creating a note, record voice live, import audio and turn meeting transcripts into structured editable text.", details: ["Document-first note creation", "Live and imported recordings", "Meeting transcription", "Rewrite, expand and organize"] },
  { id: "nova", title: "Nova", icon: Bot, copy: "Ask questions from vault context, have general conversations, research the web where supported, improve notes and perform supported Map actions. Move useful answers into continued work instead of leaving them in chat.", details: ["Vault-aware conversations", "General and web modes", "Note assistance", "Map assistance"] },
  { id: "attention", title: "Attention", icon: BellRing, copy: "Track upcoming, due-soon, overdue and completed items across individual documents and linked groups. Keep renewals, expirations and follow-ups attached to their source context.", details: ["Document reminders", "Linked-group reminders", "Upcoming and due-soon views", "Overdue and completed actions"] },
  { id: "conversion", title: "Conversion and Output", icon: FileOutput, copy: "Turn supported documents, notes, extracted information and Nova responses into formats you can continue using, including editable notes, PDF, Word and CSV where applicable.", details: ["Nova response to note", "Notes to PDF or Word", "Extracted tables to CSV", "Supported document conversion"] },
];

export default function ProductPage() {
  return <main className="min-h-screen bg-white pt-24 text-slate-900">
    <section className="bg-[#07111f] px-5 py-20 text-white sm:px-6 md:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-blue-300">NeuVault Product</p><h1 className="mt-5 text-4xl font-bold leading-tight tracking-tight sm:text-6xl">One connected system for the full document lifecycle.</h1><p className="mt-6 text-lg leading-8 text-slate-300">Bring documents in, understand what they contain, connect related context, track what needs attention and turn information into useful work.</p><Link href="/#how-it-works" className="mt-8 inline-flex rounded-xl bg-blue-500 px-6 py-3.5 font-semibold hover:bg-blue-400">See the end-to-end workflow</Link></div><div className="relative min-h-80 overflow-hidden rounded-[1.8rem] border border-white/10"><Image src="/dashboard.png" alt="NeuVault document intelligence dashboard" fill priority className="object-cover object-left-top" sizes="(min-width:1024px) 55vw, 100vw"/></div></div></section>
    <nav className="sticky top-[74px] z-20 overflow-x-auto border-b border-slate-200 bg-white/95 px-5 py-3 backdrop-blur"><div className="mx-auto flex w-max max-w-7xl gap-2">{features.map((feature) => <a key={feature.id} href={`#${feature.id}`} className="rounded-full bg-slate-100 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-blue-50 hover:text-blue-700">{feature.title}</a>)}</div></nav>
    <section className="px-5 py-16 sm:px-6 md:py-20"><div className="mx-auto max-w-7xl space-y-5">{features.map(({id,title,icon:Icon,copy,details},index) => <article id={id} key={id} className="scroll-mt-36 grid gap-6 rounded-[1.6rem] border border-slate-200 bg-slate-50 p-6 md:grid-cols-[.75fr_1.25fr] md:p-8"><div><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-600 text-white"><Icon className="h-5 w-5"/></div><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-blue-600">Capability {index+1}</p><h2 className="mt-2 text-2xl font-bold md:text-3xl">{title}</h2></div><div><p className="text-base leading-8 text-slate-600">{copy}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{details.map((detail) => <div key={detail} className="rounded-xl border border-slate-200 bg-white p-3 text-sm font-medium text-slate-700">{detail}</div>)}</div></div></article>)}</div></section>
    <section className="bg-[#07111f] px-5 py-16 text-center text-white sm:px-6"><h2 className="text-3xl font-bold">Ready to bring your documents together?</h2><p className="mx-auto mt-4 max-w-xl text-slate-300">Download NeuVault across iPhone, Android, Windows and macOS.</p><Link href="/#final-cta" className="mt-7 inline-flex rounded-xl bg-blue-500 px-6 py-3.5 font-semibold hover:bg-blue-400">Choose your platform</Link></section>
  </main>;
}
