"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import {
  ArrowRight, BellRing, Bot, Check, ChevronRight, CircleAlert, FileOutput,
  FileText, FolderInput, Mail, Map, Network, NotebookPen, Search, ShieldCheck,
  Smartphone, Waypoints,
} from "lucide-react";
import {
  ANDROID_PLAY_STORE_URL, IOS_APP_STORE_URL, MACOS_APP_STORE_URL,
  WINDOWS_MICROSOFT_STORE_URL,
} from "@/lib/seo";

const painCards = [
  ["“I know I have it somewhere.”", "But it could be in email, Downloads, a folder, a cloud drive or another device."],
  ["“I remember what it was about, not what it was called.”", "Filenames rarely match the context people remember."],
  ["“I saved it, but forgot what it needed.”", "A stored document can still contain a missed renewal, deadline or follow-up."],
  ["“These files belong together, but they live apart.”", "Agreements, invoices, meeting notes and supporting records lose their relationships across folders."],
];

const workflowSteps = [
  { title: "A document arrives", copy: "A supplier agreement arrives as a Gmail or Microsoft attachment, or appears in a watched Windows or macOS folder.", icon: Mail, label: "Desktop", view: "arrival" },
  { title: "NeuVault understands it", copy: "NeuVault creates a summary, assigns tags, organizes the file and extracts important details and dates. The user can then set a reminder directly on the document.", icon: Search, view: "understand" },
  { title: "Related information connects", copy: "Link the agreement to an invoice, previous agreement and meeting note—or review suggested same-sender attachments.", icon: Network, view: "connect" },
  { title: "Attention tracks the next step", copy: "The renewal appears alongside upcoming, due-soon and overdue items for documents and linked groups.", icon: BellRing, view: "attention" },
  { title: "The user creates an outcome", copy: "Open the agreement beside a note in the Map, ask Nova to compare terms and export the result where supported.", icon: FileOutput, view: "outcome" },
];

const capabilities = [
  { id: "bring", href: "/product/automatic-intake", eyebrow: "Bring everything together", title: "Bring documents in without filing everything manually.", copy: "Use manual capture when needed, or let NeuVault monitor the places where documents already arrive.", pain: "You should not have to repeatedly download, rename and file every document before it becomes useful.", image: "/vault.png", imageAlt: "NeuVault Vault page showing automatically organized document groups", items: ["Watched folders on Windows and macOS", "Gmail and Microsoft attachments", "Historical, fixed-range or continued email monitoring", "Uploads, mobile scans, notes and recordings"], icon: FolderInput },
  { id: "understand", href: "/product/map", eyebrow: "Understand and connect", title: "Understand what each document means—and how it relates.", copy: "NeuVault turns isolated files into searchable information with summaries, tags, groups, extracted data, dates and relationship suggestions.", pain: "Important matters rarely exist in one file, but traditional folders make related information appear disconnected.", image: "/preview.png", imageAlt: "NeuVault document preview showing summary, extracted deadline, note, location and conversion actions", items: ["Direct links and linked-document groups", "Document-to-note connections", "Same-sender attachment suggestions", "Spatial Map for reading, editing and comparison"], icon: Waypoints },
  { id: "act", href: "/product/nova", eyebrow: "Act and create", title: "Track what matters and turn information into completed work.", copy: "Attention, editable notes and Nova help you remember what happens next and continue working with information you already have.", pain: "A useful document, transcript or Nova response should not remain trapped in a folder, audio file or chat history.", image: "/smart-suggestions.png", imageAlt: "NeuVault Attention page showing active reminders, overdue documents and due-soon items", items: ["Document and linked-group reminders", "Voice and meeting transcription", "Vault-aware, general and web conversations", "Editable notes plus PDF, Word and CSV output"], icon: Bot },
];

const cases = [
  ["Professionals and consultants", "Keep contracts, reports, client files, meeting notes and follow-ups connected."],
  ["Founders and freelancers", "Organize agreements, invoices, receipts and incoming attachments without filing everything manually."],
  ["Students and researchers", "Connect papers, PDFs, recordings, notes and findings in one workspace."],
  ["Individuals and families", "Track applications, renewals and supporting records without depending on memory."],
];

const platforms = [
  ["iPhone", IOS_APP_STORE_URL], ["Android", ANDROID_PLAY_STORE_URL],
  ["macOS", MACOS_APP_STORE_URL], ["Windows", WINDOWS_MICROSOFT_STORE_URL],
];

function track(name: string, detail?: string) {
  window.dispatchEvent(new CustomEvent("neuvault:analytics", { detail: { name, detail } }));
}

function Eyebrow({ children }: { children: React.ReactNode }) {
  return <p className="text-sm font-semibold uppercase tracking-[.16em] text-blue-600">{children}</p>;
}

function WorkflowVisual({ view }: { view: string }) {
  if (view === "arrival") return <div className="grid gap-3 sm:grid-cols-2">{[[Mail,"Gmail / Microsoft attachment"],[FolderInput,"Watched desktop folder"]].map(([Icon,label]) => {const I=Icon as typeof Mail; return <div key={label as string} className="rounded-xl border border-slate-200 bg-white p-5"><I className="h-5 w-5 text-blue-600"/><p className="mt-6 font-semibold text-slate-900">{label as string}</p><span className="mt-2 inline-flex rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold uppercase text-blue-700">Desktop</span></div>})}</div>;
  if (view === "understand") return <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{["Summary", "Tags", "Group / subgroup", "Extracted details", "Important dates", "Reminder"].map((item) => <div key={item} className="rounded-xl border border-slate-200 bg-white p-4"><Check className="h-4 w-4 text-teal-600"/><p className="mt-3 text-sm font-semibold text-slate-800">{item}</p>{item === "Reminder" && <p className="mt-1 text-[11px] font-medium text-blue-600">Set on this document</p>}</div>)}</div>;
  if (view === "connect") {
    const relatedNodes = [
      { label: "Invoice", detail: "Finance record", icon: FileOutput, position: "left-[18%] top-[22%]" },
      { label: "Previous agreement", detail: "Earlier version", icon: FileText, position: "left-[82%] top-[22%]" },
      { label: "Meeting note", detail: "Renewal discussion", icon: NotebookPen, position: "left-[18%] top-[78%]" },
      { label: "Email attachment", detail: "Same sender", icon: Mail, position: "left-[82%] top-[78%]" },
    ];

    return <div className="relative min-h-[340px] overflow-hidden rounded-2xl border border-slate-200 bg-white [background-image:linear-gradient(rgba(148,163,184,.10)_1px,transparent_1px),linear-gradient(90deg,rgba(148,163,184,.10)_1px,transparent_1px)] [background-size:28px_28px]">
      <div className="absolute left-4 top-4 z-20 rounded-full border border-blue-100 bg-blue-50 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.12em] text-blue-700">Linked document group</div>
      <svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
        {[[18,22],[82,22],[18,78],[82,78]].map(([x,y]) => <g key={`${x}-${y}`}><line x1="50" y1="50" x2={x} y2={y} stroke="rgba(59,130,246,.42)" strokeWidth=".65" strokeDasharray="2 1.5"/><circle cx={x} cy={y} r="1.1" fill="#3b82f6"/><circle cx="50" cy="50" r="1.1" fill="#2563eb"/></g>)}
      </svg>
      {relatedNodes.map(({ label, detail, icon: Icon, position }) => <div key={label} className={`absolute z-10 w-[132px] -translate-x-1/2 -translate-y-1/2 rounded-xl border border-slate-200 bg-white p-3 shadow-[0_8px_24px_-14px_rgba(15,23,42,.45)] sm:w-[154px] ${position}`}><div className="flex items-center gap-2"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-blue-600"><Icon className="h-4 w-4"/></span><div className="min-w-0"><p className="truncate text-xs font-semibold text-slate-900">{label}</p><p className="mt-0.5 truncate text-[10px] text-slate-500">{detail}</p></div></div></div>)}
      <div className="absolute left-1/2 top-1/2 z-20 w-[164px] -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-blue-400 bg-blue-600 p-4 text-center text-white shadow-[0_16px_36px_-16px_rgba(37,99,235,.9)]"><Network className="mx-auto h-5 w-5"/><p className="mt-2 text-sm font-semibold">Supplier agreement</p><p className="mt-1 text-[10px] text-blue-100">4 related records</p></div>
      <div className="absolute bottom-3 left-1/2 z-20 -translate-x-1/2 rounded-full border border-slate-200 bg-white/90 px-3 py-1 text-[10px] font-medium text-slate-500 backdrop-blur">Relationships stay attached to the document</div>
    </div>;
  }
  if (view === "attention") return <div className="space-y-3">{[["Supplier renewal","Due soon","14 Sep"],["Insurance follow-up","Upcoming","21 Sep"],["Application response","Overdue","Yesterday"]].map(([title,status,date],i) => <div key={title} className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4"><div><p className="text-sm font-semibold text-slate-900">{title}</p><p className={`mt-1 text-xs ${i===2?"text-red-600":"text-slate-500"}`}>{status}</p></div><span className="text-xs text-slate-500">{date}</span></div>)}</div>;
  return <div className="grid gap-3 sm:grid-cols-[1fr_auto_1fr_auto_1fr] sm:items-center">{[[Map,"Map comparison"],[NotebookPen,"Editable note"],[FileOutput,"PDF · Word · CSV"]].map(([Icon,label],i) => {const I=Icon as typeof Map; return <div key={label as string} className="contents"><div className="rounded-xl border border-slate-200 bg-white p-5 text-center"><I className="mx-auto h-5 w-5 text-blue-600"/><p className="mt-3 text-sm font-semibold text-slate-800">{label as string}</p></div>{i<2&&<ArrowRight className="mx-auto hidden h-4 w-4 text-slate-400 sm:block"/>}</div>})}</div>;
}

export default function ProductStory() {
  const [workflow, setWorkflow] = useState(0);
  const [capability, setCapability] = useState(0);
  const activeCapability = capabilities[capability];
  const CapabilityIcon = activeCapability.icon;

  return <>
    {/* 2. Pain */}
    <section className="bg-[#f6f9fc] px-5 py-16 sm:px-6 md:py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><Eyebrow>The problem</Eyebrow><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 md:text-5xl">Your documents are not missing. They are scattered.</h2></div><div><p className="text-lg leading-8 text-slate-600">Important files live across inboxes, Downloads folders, cloud drives, screenshots, scans, recordings and old conversations. Finding the file is only the first step. You still need to understand what it contains, connect it to related information and remember what happens next.</p><p className="mt-4 text-sm font-medium leading-6 text-slate-800">This leads to repeated searching, duplicated files, missed follow-ups and information that remains unused even though it was saved.</p></div></div><div className="mt-9 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{painCards.map(([title,copy]) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5"><CircleAlert className="h-5 w-5 text-blue-600"/><h3 className="mt-5 font-semibold leading-6 text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div><p className="mx-auto mt-8 max-w-4xl text-center text-base font-semibold leading-7 text-slate-800">A useful document system should do more than store files. It should help bring information together, understand it and keep track of what matters.</p></div></section>

    {/* 3. Workflow */}
    <section id="how-it-works" className="scroll-mt-24 bg-white px-5 py-16 sm:px-6 md:py-20"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><Eyebrow>How NeuVault works</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">From an incoming document to completed work.</h2><p className="mt-4 text-lg leading-8 text-slate-600">NeuVault connects importing, organization, relationships, reminders, notes and output in one workflow.</p></div><div className="mt-10 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-2">{workflowSteps.map(({title,icon:Icon},index) => <button key={title} onClick={() => {setWorkflow(index);track("workflow_step_viewed",title)}} className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left ${workflow===index?"border-blue-300 bg-blue-50 text-blue-950":"border-slate-200 bg-white text-slate-600 hover:bg-slate-50"}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-sm font-bold ${workflow===index?"bg-blue-600 text-white":"bg-slate-100"}`}>{index+1}</span><Icon className="h-5 w-5 shrink-0"/><span className="font-semibold">{title}</span></button>)}</div><div className="rounded-[1.6rem] border border-slate-200 bg-slate-50 p-5 md:p-7"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Step {workflow+1}</p><h3 className="mt-2 text-2xl font-semibold text-slate-950">{workflowSteps[workflow].title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{workflowSteps[workflow].copy}</p></div>{workflowSteps[workflow].label&&<span className="rounded-full bg-blue-100 px-2.5 py-1 text-[10px] font-bold uppercase text-blue-700">{workflowSteps[workflow].label}</span>}</div><WorkflowVisual view={workflowSteps[workflow].view}/></div></div></div></section>

    {/* 4. Capabilities */}
    <section id="product" className="scroll-mt-24 bg-[#07111f] px-5 py-16 text-white sm:px-6 md:py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.16em] text-blue-300">The full lifecycle</p><h2 className="mt-4 text-3xl font-bold md:text-5xl">One workspace for the full document lifecycle.</h2></div><Link href="/product" onClick={() => track("product_page_clicked")} className="inline-flex items-center gap-2 font-semibold text-blue-300">Explore every capability <ChevronRight size={17}/></Link></div><div className="mt-9 flex flex-col gap-2 sm:flex-row">{capabilities.map((item,index) => <button key={item.id} onClick={() => {setCapability(index);track("capability_tab_selected",item.id)}} className={`rounded-xl border px-5 py-3 text-left text-sm font-semibold sm:text-center ${capability===index?"border-blue-400 bg-blue-500 text-white":"border-white/10 bg-white/5 text-slate-300 hover:bg-white/10"}`}>{item.eyebrow}</button>)}</div><div className="mt-5 grid overflow-hidden rounded-[1.7rem] border border-white/10 bg-white/5 lg:grid-cols-2"><div className="p-6 md:p-8"><CapabilityIcon className="h-7 w-7 text-blue-300"/><p className="mt-7 text-xs font-bold uppercase tracking-[.14em] text-blue-300">{activeCapability.eyebrow}</p><h3 className="mt-3 text-2xl font-semibold md:text-3xl">{activeCapability.title}</h3><p className="mt-4 leading-7 text-slate-300">{activeCapability.copy}</p><ul className="mt-6 grid gap-3 sm:grid-cols-2">{activeCapability.items.map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-slate-300"><Check className="mt-1 h-4 w-4 shrink-0 text-teal-300"/>{item}</li>)}</ul><p className="mt-6 border-t border-white/10 pt-5 text-sm italic leading-6 text-slate-400">{activeCapability.pain}</p></div><div className="relative min-h-72 overflow-hidden border-t border-white/10 bg-[#0d1827] lg:border-l lg:border-t-0"><Image src={activeCapability.image} alt={activeCapability.imageAlt} fill className="object-cover object-left-top" sizes="(min-width:1024px) 50vw, 100vw"/></div></div></div></section>

    {/* 5. Use cases */}
    <section className="bg-white px-5 py-16 sm:px-6 md:py-20"><div className="mx-auto max-w-7xl"><Eyebrow>Built around real document work</Eyebrow><div className="mt-4 grid gap-5 lg:grid-cols-[.82fr_1.18fr] lg:items-start lg:gap-14"><h2 className="max-w-xl text-3xl font-bold leading-tight text-slate-950 md:text-5xl">Different documents. The same underlying problem.</h2><p className="max-w-3xl text-lg leading-8 text-slate-600 lg:pt-2">Whether documents relate to work, clients, research or personal responsibilities, the challenge is keeping information connected and remembering what happens next.</p></div><div className="mt-9 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{cases.map(([title,copy]) => <article key={title} className="h-full rounded-2xl border border-slate-200 bg-slate-50 p-5"><h3 className="font-semibold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div><Link href="/business" onClick={() => track("business_cta_clicked")} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-blue-700">Looking for organization-controlled deployment? Explore NeuVault Business <ChevronRight size={16}/></Link></div></section>

    {/* 6. Privacy, platform, pricing */}
    <section id="privacy" className="scroll-mt-24 bg-[#f6f9fc] px-5 py-16 sm:px-6 md:py-20"><div className="mx-auto max-w-7xl"><div className="text-center"><Eyebrow>Trust, access and value</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">Private by design. Available where you work.</h2></div><div className="mt-10 grid gap-4 lg:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-6"><ShieldCheck className="h-6 w-6 text-blue-600"/><h3 className="mt-6 text-xl font-semibold text-slate-950">Your documents remain under your control.</h3><p className="mt-3 text-sm leading-7 text-slate-600">NeuVault is local-first. Original documents remain on your device by default instead of becoming part of a central NeuVault storage service. Backups are encrypted and user-controlled; AI processing runs when chosen, with transient handling where applicable. Authorized email and folder integrations can be disconnected.</p><Link href="/privacy-policy" className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-blue-700">Privacy details <ChevronRight size={15}/></Link></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><Smartphone className="h-6 w-6 text-blue-600"/><h3 className="mt-6 text-xl font-semibold text-slate-950">iOS, Android, macOS and Windows.</h3><p className="mt-3 text-sm leading-7 text-slate-600"><strong>Mobile:</strong> scan, record voice, create notes, use Nova and access organized files.<br/><strong>Desktop:</strong> monitor folders and email, use the larger Map and work side by side.</p><div className="mt-5 flex flex-wrap gap-2">{platforms.map(([label,href]) => <a key={label} href={href} target="_blank" rel="noreferrer" onClick={() => track("platform_selected",label)} className="rounded-full border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:border-blue-300">{label}</a>)}</div></article><article id="pricing" className="scroll-mt-24 rounded-2xl border border-blue-200 bg-blue-50 p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-700">Explorer</p><h3 className="mt-3 text-3xl font-bold text-slate-950">500 free credits</h3><p className="mt-1 font-semibold text-blue-700">Available for 14 days</p><p className="mt-4 text-sm leading-7 text-slate-600">Continue using NeuVault afterward and add credits when you choose supported AI or OCR features.</p><p className="mt-5 rounded-xl bg-white p-3 text-sm font-semibold text-slate-800">Free to store documents. Credits only when you choose to use AI.</p><div className="mt-5 flex flex-wrap gap-2 text-xs text-slate-600"><span>Personal · $10</span><span>·</span><span>Pro · $15</span><span>·</span><span>Premium · $20</span></div><Link href="/pricing" onClick={() => track("pricing_viewed")} className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-blue-700">View full pricing <ChevronRight size={15}/></Link></article></div></div></section>

    {/* 7. CTA */}
    <section id="final-cta" className="bg-[#07111f] px-5 py-16 text-center text-white sm:px-6 md:py-20"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-bold md:text-5xl">Stop managing documents one file at a time.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-300">Bring scattered documents into one private workspace that helps organize, connect and track what matters.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={() => {track("final_download_clicked");window.dispatchEvent(new Event("neuvault:open-downloads"))}} className="rounded-xl bg-blue-500 px-6 py-3.5 font-semibold hover:bg-blue-400">Download NeuVault</button><a href="#platform-choices" className="rounded-xl border border-white/15 bg-white/5 px-6 py-3.5 font-semibold hover:bg-white/10">Choose your platform</a></div><div id="platform-choices" className="mt-6 flex flex-wrap justify-center gap-2">{platforms.map(([label,href]) => <a key={label} href={href} target="_blank" rel="noreferrer" onClick={() => track("platform_selected",label)} className="rounded-full border border-white/15 px-4 py-2 text-sm text-slate-300 hover:bg-white/10">{label}</a>)}</div></div></section>
  </>;
}
