import Link from "next/link";
import {
  Bot, CalendarClock, Check, ChevronRight, CircleAlert, FileAudio,
  FileOutput, FileText, FolderInput, Mail, Map, Mic2, Network, NotebookPen,
  ScanLine, Search, ShieldCheck, Smartphone, Sparkles, Upload, Waypoints,
} from "lucide-react";

const intakeGroups = [
  { label: "Automatic", tone: "blue", items: [{ title: "Watched folders", copy: "Select folders on Windows or macOS. NeuVault detects and imports new documents.", icon: FolderInput, badge: "Desktop" }, { title: "Email attachments", copy: "Connect Google or Microsoft, choose a historical date range, then continue monitoring new attachments.", icon: Mail, badge: "Desktop · Yahoo coming soon" }] },
  { label: "Manual", tone: "teal", items: [{ title: "Upload files", copy: "Add PDFs, Word documents, images and other supported files when you choose.", icon: Upload }, { title: "Scan documents", copy: "Capture paper documents on mobile and bring them into the same workspace.", icon: ScanLine, badge: "Mobile" }] },
  { label: "Created in NeuVault", tone: "violet", items: [{ title: "Notes", copy: "Write directly or select supporting documents first and create a note around them.", icon: NotebookPen }, { title: "Voice and meetings", copy: "Record live or import audio, then turn it into structured, editable text.", icon: Mic2 }] },
];

const outputs = ["Summary", "Tags", "Group and subgroup", "Extracted data", "Important dates", "Document type", "Related records", "Attention signals"];
const useCases = [
  ["Professionals", "Keep contracts, reports, invoices, meeting notes and follow-up dates connected."],
  ["Founders & freelancers", "Monitor client files, proposals, receipts and agreements without manually filing every attachment."],
  ["Students & researchers", "Connect papers, PDFs, notes, recordings and findings in one visual workspace."],
  ["Consultants", "Organize project documents, transcribe meetings and turn findings into editable reports."],
  ["Individuals & families", "Track personal records, applications, renewals and supporting documents."],
];

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-sm font-semibold uppercase tracking-[.16em] text-blue-600">{children}</p>; }

export default function ProductStory() {
  return <>
    <section className="bg-[#f6f9fc] px-5 py-20 sm:px-6 md:py-24">
      <div className="mx-auto max-w-6xl">
        <div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end">
          <div><Eyebrow>The problem</Eyebrow><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 md:text-5xl">Your documents are not missing. They are scattered.</h2></div>
          <p className="text-lg leading-8 text-slate-600">Important files live across inboxes, Downloads, cloud drives, screenshots, scans and old conversations. Finding the file is only the first step—you still need to understand it and remember what happens next.</p>
        </div>
        <div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["An invoice buried in email", "A contract sitting in Downloads", "A renewal date hidden in a PDF", "Meeting notes trapped in audio", "Supporting records split across folders", "A file remembered by context, not name"].map((item, i) => <div key={item} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm font-medium text-slate-700"><CircleAlert className={`h-5 w-5 ${i === 2 ? "text-amber-500" : "text-slate-400"}`} />{item}</div>)}</div>
      </div>
    </section>

    <section id="intake" className="scroll-mt-24 bg-white px-5 py-20 sm:px-6 md:py-28">
      <div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><Eyebrow>Automatic intake</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">Documents come to NeuVault, automatically.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Add documents manually when you need to, or let NeuVault monitor the places where new files already appear.</p></div>
      <div className="mt-12 grid gap-5 lg:grid-cols-3">{intakeGroups.map((group) => <div key={group.label} className="rounded-[1.6rem] border border-slate-200 bg-slate-50 p-5"><div className="mb-4 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-blue-500"/><h3 className="font-semibold text-slate-950">{group.label}</h3></div><div className="space-y-3">{group.items.map(({ title, copy, icon: Icon, badge }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><Icon className="h-5 w-5 text-blue-600"/>{badge && <span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-semibold uppercase text-blue-700">{badge}</span>}</div><h4 className="mt-4 font-semibold text-slate-950">{title}</h4><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div>)}</div>
      <p className="mt-5 text-center text-sm text-slate-500">Email integration is available on desktop. You choose the import range and whether monitoring continues afterward.</p></div>
    </section>

    <section id="intelligence" className="scroll-mt-24 bg-[#07111f] px-5 py-20 text-white sm:px-6 md:py-28">
      <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><Eyebrow>Document intelligence</Eyebrow><h2 className="mt-4 text-3xl font-bold md:text-5xl">More than storage. NeuVault understands each document.</h2><p className="mt-5 text-lg leading-8 text-slate-300">NeuVault turns unstructured files into organized, searchable information—without making you rename and file everything by hand.</p></div>
      <div className="rounded-[1.7rem] border border-white/10 bg-white/5 p-5 md:p-7"><div className="grid gap-5 md:grid-cols-[.75fr_1.25fr]"><div className="rounded-2xl border border-white/10 bg-[#0c1726] p-5"><p className="text-xs uppercase tracking-widest text-slate-500">Original file</p><FileText className="mt-8 h-10 w-10 text-blue-300"/><p className="mt-4 break-all font-medium">Supplier_Agreement_Final_v3.pdf</p><p className="mt-2 text-sm text-slate-500">42 pages · PDF</p></div><div className="grid grid-cols-2 gap-3">{outputs.map((item, index) => <div key={item} className={`rounded-xl border p-3 ${index === 4 ? "border-amber-400/30 bg-amber-400/10" : "border-white/10 bg-white/5"}`}><Check className={`h-4 w-4 ${index === 4 ? "text-amber-300" : "text-teal-300"}`}/><p className="mt-2 text-sm font-medium">{item}</p></div>)}</div></div></div></div>
    </section>

    <section id="connected" className="scroll-mt-24 bg-white px-5 py-20 sm:px-6 md:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><Eyebrow>Linked documents</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">Your documents make more sense together.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Link documents, notes, scans and records so you can find information through context rather than filenames or folders. NeuVault can also suggest relationships, including attachments from the same sender.</p><div className="mt-7 grid gap-3"><div className="rounded-xl border border-slate-200 p-4"><p className="text-sm font-semibold text-slate-950">Traditional folders</p><p className="mt-1 text-sm text-slate-600">A document belongs in one location.</p></div><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="text-sm font-semibold text-blue-900">NeuVault links</p><p className="mt-1 text-sm text-blue-800">A document stays connected to every context where it matters.</p></div></div></div><div className="relative min-h-[360px] rounded-[1.7rem] border border-slate-200 bg-slate-50 p-6"><div className="absolute left-[38%] top-[43%] z-10 rounded-2xl bg-blue-600 p-5 text-center text-white shadow-xl"><Network className="mx-auto h-6 w-6"/><p className="mt-2 text-sm font-semibold">Client renewal</p></div>{[["Agreement","8%","10%"],["Invoice","68%","10%"],["Meeting note","7%","70%"],["Email attachment","68%","72%"]].map(([name,left,top]) => <div key={name} style={{left,top}} className="absolute rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 shadow-sm"><FileText className="mb-2 h-4 w-4 text-blue-500"/>{name}</div>)}<svg className="absolute inset-0 h-full w-full text-blue-300" aria-hidden><line x1="45%" y1="48%" x2="18%" y2="22%" stroke="currentColor"/><line x1="55%" y1="48%" x2="75%" y2="22%" stroke="currentColor"/><line x1="45%" y1="56%" x2="18%" y2="78%" stroke="currentColor"/><line x1="55%" y1="56%" x2="76%" y2="79%" stroke="currentColor"/></svg></div></div></div></section>

    <section id="map" className="scroll-mt-24 bg-[#f6f9fc] px-5 py-20 sm:px-6 md:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><Eyebrow>The NeuVault Map</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">Work with documents spatially.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The NeuVault Map is a spatial document workspace where files, editable notes and relationships can be explored together.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-[1.7rem] border border-slate-200 bg-[#0b1625] p-5 text-white shadow-xl"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="flex items-center gap-2 font-semibold"><Map className="text-blue-300"/>Research map</span><span className="text-xs text-slate-400">5 connected items</span></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="space-y-3"><div className="rounded-xl border border-blue-400/30 bg-blue-400/10 p-4">Supplier agreement.pdf</div><div className="ml-8 rounded-xl border border-white/10 p-4">Meeting transcript</div><div className="rounded-xl border border-white/10 p-4">Renewal analysis</div></div><div className="rounded-xl bg-white p-5 text-slate-800"><p className="text-xs uppercase tracking-widest text-slate-400">Editable note</p><h3 className="mt-3 font-semibold">Renewal recommendation</h3><p className="mt-3 text-sm leading-6 text-slate-600">Compare the existing agreement with the proposed terms. Confirm the notice window and updated pricing.</p><div className="mt-6 rounded-lg bg-blue-50 p-3 text-xs text-blue-700">Nova: Merge selected notes</div></div></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{["Arrange document and note nodes", "Read a document beside an editable note", "Compare two documents or two notes", "Ask Nova to create, merge and organize notes"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm font-medium text-slate-700"><Waypoints className="h-5 w-5 shrink-0 text-blue-600"/>{item}</div>)}</div></div></div></section>

    <section id="notes" className="scroll-mt-24 bg-white px-5 py-20 sm:px-6 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div><Eyebrow>Notes, voice and meetings</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">Turn thoughts and conversations into structured work.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Write notes, record ideas, import existing audio or capture meetings in real time. Transcripts become structured, editable text that can stay connected to the documents being discussed.</p><div className="mt-7 rounded-2xl border border-blue-200 bg-blue-50 p-5"><p className="font-semibold text-blue-950">A document-first note workflow</p><p className="mt-2 text-sm leading-6 text-blue-800">Select the supporting documents first, then create and edit a note around them—with Nova available to rewrite, expand, summarize or organize.</p></div></div><div className="grid gap-4 sm:grid-cols-2">{[["Write with Nova",NotebookPen],["Live voice note",Mic2],["Import a recording",FileAudio],["Transcribe a meeting",Sparkles]].map(([label, Icon]) => { const I=Icon as typeof NotebookPen; return <div key={label as string} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><I className="h-6 w-6 text-blue-600"/><h3 className="mt-8 font-semibold text-slate-950">{label as string}</h3><p className="mt-2 text-sm text-slate-600">Structured, editable and connected to your document context.</p></div>})}</div></div></section>

    <section id="nova" className="scroll-mt-24 bg-[#07111f] px-5 py-20 text-white sm:px-6 md:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>Nova</Eyebrow><h2 className="mt-4 text-3xl font-bold md:text-5xl">Ask, research, write and act with Nova.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Use document-aware conversations, general questions, web research where supported, note assistance and Map actions. A useful answer does not have to remain trapped in chat.</p></div><div className="grid gap-3 sm:grid-cols-2">{[["Vault-aware",Search,"Answers from summaries, tags, dates and linked records."],["General and web",Bot,"Ask broader questions or research current information where supported."],["Notes and Map",Map,"Write, structure and perform supported actions in the spatial workspace."],["Create an output",FileOutput,"Turn a response into an editable note, PDF, Word document or CSV."]].map(([title,Icon,copy]) => {const I=Icon as typeof Bot; return <div key={title as string} className="rounded-2xl border border-white/10 bg-white/5 p-5"><I className="h-5 w-5 text-blue-300"/><h3 className="mt-5 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy as string}</p></div>})}</div></div></div></section>

    <section id="attention" className="scroll-mt-24 bg-white px-5 py-20 sm:px-6 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><Eyebrow>Attention</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">Know what needs attention before it is forgotten.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Track reminders, follow-ups, renewals, expirations and future events across individual documents and linked groups. Attention brings them into one clear view.</p></div><div className="rounded-[1.7rem] border border-slate-200 bg-slate-50 p-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Upcoming","12"],["Due soon","4"],["Overdue","2"],["Completed","19"]].map(([label,count],i) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className={`mt-2 text-2xl font-bold ${i===2?"text-red-600":"text-slate-950"}`}>{count}</p></div>)}</div><div className="mt-4 space-y-2">{[["Supplier agreement renewal","14 Sep","Due soon"],["Insurance follow-up","21 Sep","Upcoming"],["Complete passport application","Yesterday","Overdue"]].map(([title,date,status]) => <div key={title} className="flex items-center justify-between gap-3 rounded-xl bg-white p-4"><div className="flex items-center gap-3"><CalendarClock className="h-5 w-5 text-blue-600"/><div><p className="text-sm font-semibold text-slate-900">{title}</p><p className="text-xs text-slate-500">{status}</p></div></div><span className="text-xs font-medium text-slate-500">{date}</span></div>)}</div></div></div></section>

    <section id="conversion" className="scroll-mt-24 bg-[#f6f9fc] px-5 py-20 sm:px-6 md:py-24"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-2"><div><Eyebrow>Conversion and output</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">Turn information into the format you need.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Convert supported documents, notes and useful Nova responses into practical formats without rebuilding the content manually.</p></div><div className="grid gap-3 sm:grid-cols-2">{["Meeting summary → Word", "Extracted table → CSV", "Completed note → PDF", "Nova response → editable note"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-700"><FileOutput className="h-5 w-5 text-blue-600"/>{item}</div>)}</div></div></div></section>

    <section id="platforms" className="scroll-mt-24 bg-white px-5 py-20 sm:px-6 md:py-28"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-3xl text-center"><Eyebrow>Cross-platform</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">One NeuVault across your devices.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Core organization, search, notes, Attention and Nova span supported experiences. Some capabilities are tailored to where they work best.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["iPhone","Scanning and mobile capture"],["Android","Scanning and mobile capture"],["macOS","Folder and email monitoring"],["Windows","Folder and email monitoring"]].map(([name,copy]) => <div key={name} className="rounded-2xl border border-slate-200 p-5"><Smartphone className="h-6 w-6 text-blue-600"/><h3 className="mt-8 text-xl font-semibold text-slate-950">{name}</h3><p className="mt-2 text-sm text-slate-600">{copy}</p></div>)}</div></div></section>

    <section id="privacy" className="scroll-mt-24 bg-[#07111f] px-5 py-20 text-white sm:px-6 md:py-28"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><Eyebrow>Privacy and storage</Eyebrow><h2 className="mt-4 text-3xl font-bold md:text-5xl">Your documents remain under your control.</h2><p className="mt-5 text-lg leading-8 text-slate-300">NeuVault is local-first. Original documents remain on your device by default unless you choose a supported backup or integration workflow. AI processing begins when you choose an AI-supported feature.</p><Link href="/privacy-policy" className="mt-7 inline-flex items-center gap-2 font-semibold text-blue-300 hover:text-blue-200">Read the privacy architecture <ChevronRight size={17}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{["Original files stored on-device by default", "Encrypted backup options you control", "No central NeuVault document drive", "On-demand AI processing for chosen features"].map((item) => <div key={item} className="flex gap-3 rounded-xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-slate-300"><ShieldCheck className="h-5 w-5 shrink-0 text-teal-300"/>{item}</div>)}</div></div></section>

    <section className="bg-white px-5 py-20 sm:px-6 md:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><Eyebrow>Built for real work</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">One workspace. Many document-heavy lives.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{useCases.map(([title,copy]) => <article key={title} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h3 className="font-semibold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>

    <section className="bg-[#f6f9fc] px-5 py-20 sm:px-6 md:py-24"><div className="mx-auto max-w-5xl"><div className="text-center"><Eyebrow>Questions, answered</Eyebrow><h2 className="mt-4 text-3xl font-bold text-slate-950 md:text-5xl">What to know before you download.</h2></div><div className="mt-10 divide-y divide-slate-200 rounded-[1.6rem] border border-slate-200 bg-white px-5 md:px-7">{[
      ["Where are my documents stored?", "NeuVault is local-first. Original documents remain on your device by default unless you choose a supported backup or integration workflow."],
      ["Can NeuVault import email attachments and monitor folders?", "Yes, on desktop. Connect Google or Microsoft email, choose a historical range and optionally continue monitoring. Select Windows or macOS folders to watch for new files. Yahoo email support is coming soon."],
      ["Can I use NeuVault without AI credits?", "Yes. Storage and non-AI vault functionality remain available. Credits are used only when you choose a supported AI or OCR action."],
      ["Can NeuVault transcribe meetings?", "Yes. Record live or import audio, then turn the transcript into structured, editable text connected to your documents."],
      ["Can I link, compare and convert documents?", "Yes. Link related records, compare documents and notes in the Map, and turn supported documents, notes and Nova responses into PDF, Word, CSV or editable notes where applicable."],
    ].map(([question,answer]) => <details key={question} className="group py-5"><summary className="cursor-pointer list-none pr-8 font-semibold text-slate-950 marker:hidden">{question}<span className="float-right text-blue-600 group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></div></section>
  </>;
}
